
workflows:
  ios-native-workflow:
    name: Cash App
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.cashapp.prop
      vars:
        BUNDLE_ID: com.cashapp.prop
        XCODE_WORKSPACE: "cashapp_prop.xcworkspace" # <-- Put the name of your Xcode workspace here
        XCODE_SCHEME: "Cash App Prop" # <-- Put the name of your Xcode scheme here
      xcode: latest
scripts:
  - name: Build ipa for distribution
    script: | 
      xcode-project build-ipa \
        --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
        --scheme "$XCODE_SCHEME"
artifacts:
  - build/ios/ipa/*.ipa
  - /tmp/xcodebuild_logs/*.log
  - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
  - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
